//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseScore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseScore.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Label_Available {
            get {
                return ResourceManager.GetString("Label_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string Label_Basic {
            get {
                return ResourceManager.GetString("Label_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating....
        /// </summary>
        internal static string Label_Calculating {
            get {
                return ResourceManager.GetString("Label_Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating {0} Records.
        /// </summary>
        internal static string Label_CalculatingRecords {
            get {
                return ResourceManager.GetString("Label_CalculatingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Details.
        /// </summary>
        internal static string Label_ChartDetails {
            get {
                return ResourceManager.GetString("Label_ChartDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Label_Clear {
            get {
                return ResourceManager.GetString("Label_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climbs.
        /// </summary>
        internal static string Label_Climbs {
            get {
                return ResourceManager.GetString("Label_Climbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Score.
        /// </summary>
        internal static string Label_CourseScore {
            get {
                return ResourceManager.GetString("Label_CourseScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycling.
        /// </summary>
        internal static string Label_Cycling {
            get {
                return ResourceManager.GetString("Label_Cycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        internal static string Label_Defaults {
            get {
                return ResourceManager.GetString("Label_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descents.
        /// </summary>
        internal static string Label_Descents {
            get {
                return ResourceManager.GetString("Label_Descents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Percent.
        /// </summary>
        internal static string Label_DistancePercent {
            get {
                return ResourceManager.GetString("Label_DistancePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation Percent.
        /// </summary>
        internal static string Label_ElevationPercent {
            get {
                return ResourceManager.GetString("Label_ElevationPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string Label_End {
            get {
                return ResourceManager.GetString("Label_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eval version limited to {0} distance categories.
        /// </summary>
        internal static string Label_EvalCategoryLimit {
            get {
                return ResourceManager.GetString("Label_EvalCategoryLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eval version locked to evaluate previous {0} days.  See settings page to unlock..
        /// </summary>
        internal static string Label_EvalHistoryLimit {
            get {
                return ResourceManager.GetString("Label_EvalHistoryLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        internal static string Label_Fill {
            get {
                return ResourceManager.GetString("Label_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find similar hills in all activities for current category.
        /// </summary>
        internal static string Label_FindHillsLikeThis {
            get {
                return ResourceManager.GetString("Label_FindHillsLikeThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find this route in all activities for current category.
        /// </summary>
        internal static string Label_FindRoutesLikeThis {
            get {
                return ResourceManager.GetString("Label_FindRoutesLikeThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find this hill in all activities for current category.
        /// </summary>
        internal static string Label_FindThisHillInAllActivites {
            get {
                return ResourceManager.GetString("Label_FindThisHillInAllActivites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find this split in all activities for current category.
        /// </summary>
        internal static string Label_FindThisSplitInAllActivities {
            get {
                return ResourceManager.GetString("Label_FindThisSplitInAllActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardest.
        /// </summary>
        internal static string Label_Hardest {
            get {
                return ResourceManager.GetString("Label_Hardest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardest Climb.
        /// </summary>
        internal static string Label_HardestClimb {
            get {
                return ResourceManager.GetString("Label_HardestClimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill Classification.
        /// </summary>
        internal static string Label_HillClassification {
            get {
                return ResourceManager.GetString("Label_HillClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill Distance Required.
        /// </summary>
        internal static string Label_HillDistanceRequired {
            get {
                return ResourceManager.GetString("Label_HillDistanceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill Elevation Required.
        /// </summary>
        internal static string Label_HillElevationRequired {
            get {
                return ResourceManager.GetString("Label_HillElevationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill Finder Settings.
        /// </summary>
        internal static string Label_HillFinderSettings {
            get {
                return ResourceManager.GetString("Label_HillFinderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill id.
        /// </summary>
        internal static string Label_HillId {
            get {
                return ResourceManager.GetString("Label_HillId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill Score.
        /// </summary>
        internal static string Label_HillScore {
            get {
                return ResourceManager.GetString("Label_HillScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill Score Equation.
        /// </summary>
        internal static string Label_HillScoreEquation {
            get {
                return ResourceManager.GetString("Label_HillScoreEquation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Settings....
        /// </summary>
        internal static string Label_ListSettings {
            get {
                return ResourceManager.GetString("Label_ListSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest.
        /// </summary>
        internal static string Label_Longest {
            get {
                return ResourceManager.GetString("Label_Longest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest Climb.
        /// </summary>
        internal static string Label_LongestClimb {
            get {
                return ResourceManager.GetString("Label_LongestClimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Descent Elevation Change.
        /// </summary>
        internal static string Label_MaxDescentElevationChange {
            get {
                return ResourceManager.GetString("Label_MaxDescentElevationChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Descent Length.
        /// </summary>
        internal static string Label_MaxDescentLength {
            get {
                return ResourceManager.GetString("Label_MaxDescentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Average Grade.
        /// </summary>
        internal static string Label_MinAvgGrade {
            get {
                return ResourceManager.GetString("Label_MinAvgGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Grade.
        /// </summary>
        internal static string Label_MinGrade {
            get {
                return ResourceManager.GetString("Label_MinGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall.
        /// </summary>
        internal static string Label_Overall {
            get {
                return ResourceManager.GetString("Label_Overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Label_Running {
            get {
                return ResourceManager.GetString("Label_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Label_Score {
            get {
                return ResourceManager.GetString("Label_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Charts.
        /// </summary>
        internal static string Label_SelectedCharts {
            get {
                return ResourceManager.GetString("Label_SelectedCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        internal static string Label_Sport {
            get {
                return ResourceManager.GetString("Label_Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steepest.
        /// </summary>
        internal static string Label_Steepest {
            get {
                return ResourceManager.GetString("Label_Steepest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steepest Climb.
        /// </summary>
        internal static string Label_SteepestClimb {
            get {
                return ResourceManager.GetString("Label_SteepestClimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Label_Summary {
            get {
                return ResourceManager.GetString("Label_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAM.
        /// </summary>
        internal static string Label_VAM {
            get {
                return ResourceManager.GetString("Label_VAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W/kg.
        /// </summary>
        internal static string Label_wKg {
            get {
                return ResourceManager.GetString("Label_wKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on activity.
        /// </summary>
        internal static string Message_ErrorExporting {
            get {
                return ResourceManager.GetString("Message_ErrorExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting elevation data for.
        /// </summary>
        internal static string Message_ExportingElevation {
            get {
                return ResourceManager.GetString("Message_ExportingElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character..
        /// </summary>
        internal static string Message_InvalidCharacter {
            get {
                return ResourceManager.GetString("Message_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This hill does not have GPS data for it. Exact hills will not be found..
        /// </summary>
        internal static string Message_NoGPS {
            get {
                return ResourceManager.GetString("Message_NoGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the current descent&apos;s distance covered divided by the hill&apos;s overall distance is greater than this value, the descent isn&apos;t part of this hill (ex .33)..
        /// </summary>
        internal static string Tooltip_DistancePercent {
            get {
                return ResourceManager.GetString("Tooltip_DistancePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the current descent&apos;s elevation change divided by the hill&apos;s overall elevation gain is greater than this value, the descent isn&apos;t part of this hill (ex .33)..
        /// </summary>
        internal static string Tooltip_ElevationPercent {
            get {
                return ResourceManager.GetString("Tooltip_ElevationPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance covered to call this a hill..
        /// </summary>
        internal static string Tooltip_HillDistanceRequired {
            get {
                return ResourceManager.GetString("Tooltip_HillDistanceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required elevation change to call this a hill..
        /// </summary>
        internal static string Tooltip_HillElevationRequired {
            get {
                return ResourceManager.GetString("Tooltip_HillElevationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum elevation change for a single descent before it breaks up the hill (ex &apos;200&apos; for a 200m drop)..
        /// </summary>
        internal static string Tooltip_MaxDescentElevationChange {
            get {
                return ResourceManager.GetString("Tooltip_MaxDescentElevationChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length for a single descent before it breaks up the hill..
        /// </summary>
        internal static string Tooltip_MaxDescentLength {
            get {
                return ResourceManager.GetString("Tooltip_MaxDescentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum average grade for this to be considered a hill (ex .04)..
        /// </summary>
        internal static string Tooltip_MinAvgGrade {
            get {
                return ResourceManager.GetString("Tooltip_MinAvgGrade", resourceCulture);
            }
        }
    }
}
